name: Release Artifacts

on:
  push:
    tags: 
      - "v*.*.*"
  workflow_dispatch: 
    inputs: 
      tag: 
        description: "Tag to build artifact" 
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CGO_ENABLED: 0
    
    steps:
    - name: Check out source code 
      uses: actions/checkout@v2
      with: 
        ref: "${{ github.event.inputs.tag }}"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    # Linux 
    - name: Build linux x86-64 artifact 
      env: 
        GOOS: linux
        GOARCH: amd64
      run: go build -trimpath -o bin/croned-twitcasting-recorder_${GOOS}_${GOARCH}
    
    - name: Build linux arm64 artifact 
      env: 
        GOOS: linux
        GOARCH: arm64
      run: go build -trimpath -o bin/croned-twitcasting-recorder_${GOOS}_${GOARCH}
    
    # macOS
    - name: Build macOS x86-64 artifact 
      env: 
        GOOS: darwin
        GOARCH: amd64
      run: go build -trimpath -o bin/croned-twitcasting-recorder_${GOOS}_${GOARCH}
    
    - name: Build macOS arm64 artifact 
      env: 
        GOOS: darwin
        GOARCH: arm64
      run: go build -trimpath -o bin/croned-twitcasting-recorder_${GOOS}_${GOARCH}
    
    # Windows 
    - name: Build Windows x86-64 artifact 
      env: 
        GOOS: windows
        GOARCH: amd64
      run: go build -trimpath -o bin/croned-twitcasting-recorder_${GOOS}_${GOARCH}.exe
    
    - name: Copy example config 
      run: cp config_example.yaml bin/config_example.yaml
    
    - name: Release artifacts 
      uses: softprops/action-gh-release@v1
      with: 
        prerelease: true
        tag_name: "${{ github.ref }}"
        files: bin/*
